export var hl = `
define extension "py"

set comment.reverseOnClose "/*"
set comment.inline "//"

set string "'"
set string "\\""

set operator ";"
set operator ","
set operator "="
set operator "!"
set operator "."
set operator "{"
set operator "}"
set operator "["
set operator "]"
set operator "("
set operator ")"
set operator ">"
set operator "<"
set operator "+"
set operator "-"
set operator "*"
set operator "/"
set operator ":"
set operator " "
set operator "\\t"

set keyword "abstract"
set keyword "goto"
set keyword "package"
set keyword "synchronized"
set keyword "implements"
set keyword "private"
set keyword "this"
set keyword "protected"
set keyword "import"
set keyword "throws"
set keyword "enum"
set keyword "instanceof"
set keyword "transient"
set keyword "extends"
set keyword "final"
set keyword "interface"
set keyword "static"
set keyword "class"
set keyword "strictfp"
set keyword "volatile"
set keyword "native"
set keyword "const"

set command "continue"
set command "for"
set command "new"
set command "switch"
set command "assert"
set command "do"
set command "if"
set command "break"
set command "throw"
set command "else"
set command "case"
set command "return"
set command "catch"
set command "try"
set command "default"
set command "finally"
set command "while"

set object "boolean"
set object "double"
set object "byte"
set object "int"
set object "short"
set object "char"
set object "void"
set object "long"
`;
